### ISSUE TITLE
News ticker

### ISSUE THREAD

**Issue by krishnamrith12** [SanskritPanini/sanskritpanini.github.io#2]
- Add a bullet point for each news item
- Reduce the padding space below the ticker
- Change the background colour to what is used in say applications. Since About the hackathon and Recent updates are completely different blocks, both needs to be distinguished using colour.

Also, try incorporating the nt-example2 in the ticker in the following URL https://risq.github.io/jquery-advanced-news-ticker/index.html

**Comment by SriramKrishnan8** [comment]
Removed the existing "recent updates" and added the nt-example2 newsticker as suggested.
